/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2024-07-16 18:20:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class get_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1707279993000L));
    _jspx_dependants.put("jar:file:/Users/bg/Desktop/SpringFramework01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/fd01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1707279993000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1694513530145L));
    _jspx_dependants.put("jar:file:/Users/bg/Desktop/SpringFramework01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/fd01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>SB Admin 2 - Bootstrap Admin Theme</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- MetisMenu CSS -->\n");
      out.write("    <link href=\"/resources/vendor/metisMenu/metisMenu.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- DataTables CSS -->\n");
      out.write("    <link href=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- DataTables Responsive CSS -->\n");
      out.write("    <link href=\"/resources/vendor/datatables-responsive/dataTables.responsive.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("        <!-- Navigation -->\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.html\">SB Admin v2.0</a>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-header -->\n");
      out.write("\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\n");
      out.write("                        <i class=\"fa fa-envelope fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-messages\">\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <strong>John Smith</strong>\n");
      out.write("                                    <span class=\"pull-right text-muted\">\n");
      out.write("                                        <em>Yesterday</em>\n");
      out.write("                                    </span>\n");
      out.write("                                </div>\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <strong>John Smith</strong>\n");
      out.write("                                    <span class=\"pull-right text-muted\">\n");
      out.write("                                        <em>Yesterday</em>\n");
      out.write("                                    </span>\n");
      out.write("                                </div>\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <strong>John Smith</strong>\n");
      out.write("                                    <span class=\"pull-right text-muted\">\n");
      out.write("                                        <em>Yesterday</em>\n");
      out.write("                                    </span>\n");
      out.write("                                </div>\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\n");
      out.write("                                <strong>Read All Messages</strong>\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- /.dropdown-messages -->\n");
      out.write("                </li>\n");
      out.write("                <!-- /.dropdown -->\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\n");
      out.write("                        <i class=\"fa fa-tasks fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-tasks\">\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <p>\n");
      out.write("                                        <strong>Task 1</strong>\n");
      out.write("                                        <span class=\"pull-right text-muted\">40% Complete</span>\n");
      out.write("                                    </p>\n");
      out.write("                                    <div class=\"progress progress-striped active\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%\">\n");
      out.write("                                            <span class=\"sr-only\">40% Complete (success)</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <p>\n");
      out.write("                                        <strong>Task 2</strong>\n");
      out.write("                                        <span class=\"pull-right text-muted\">20% Complete</span>\n");
      out.write("                                    </p>\n");
      out.write("                                    <div class=\"progress progress-striped active\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%\">\n");
      out.write("                                            <span class=\"sr-only\">20% Complete</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <p>\n");
      out.write("                                        <strong>Task 3</strong>\n");
      out.write("                                        <span class=\"pull-right text-muted\">60% Complete</span>\n");
      out.write("                                    </p>\n");
      out.write("                                    <div class=\"progress progress-striped active\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\n");
      out.write("                                            <span class=\"sr-only\">60% Complete (warning)</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <p>\n");
      out.write("                                        <strong>Task 4</strong>\n");
      out.write("                                        <span class=\"pull-right text-muted\">80% Complete</span>\n");
      out.write("                                    </p>\n");
      out.write("                                    <div class=\"progress progress-striped active\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\n");
      out.write("                                            <span class=\"sr-only\">80% Complete (danger)</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\n");
      out.write("                                <strong>See All Tasks</strong>\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- /.dropdown-tasks -->\n");
      out.write("                </li>\n");
      out.write("                <!-- /.dropdown -->\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\n");
      out.write("                        <i class=\"fa fa-bell fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-alerts\">\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <i class=\"fa fa-comment fa-fw\"></i> New Comment\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <i class=\"fa fa-twitter fa-fw\"></i> 3 New Followers\n");
      out.write("                                    <span class=\"pull-right text-muted small\">12 minutes ago</span>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <i class=\"fa fa-envelope fa-fw\"></i> Message Sent\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <i class=\"fa fa-tasks fa-fw\"></i> New Task\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div>\n");
      out.write("                                    <i class=\"fa fa-upload fa-fw\"></i> Server Rebooted\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li>\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\n");
      out.write("                                <strong>See All Alerts</strong>\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- /.dropdown-alerts -->\n");
      out.write("                </li>\n");
      out.write("                <!-- /.dropdown -->\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-user fa-fw\"></i> User Profile</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-gear fa-fw\"></i> Settings</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"divider\"></li>\n");
      out.write("                        <li><a href=\"login.html\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- /.dropdown-user -->\n");
      out.write("                </li>\n");
      out.write("                <!-- /.dropdown -->\n");
      out.write("            </ul>\n");
      out.write("            <!-- /.navbar-top-links -->\n");
      out.write("\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\n");
      out.write("                        <li class=\"sidebar-search\">\n");
      out.write("                            <div class=\"input-group custom-search-form\">\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("                                <span class=\"input-group-btn\">\n");
      out.write("                                <button class=\"btn btn-default\" type=\"button\">\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\n");
      out.write("                                </button>\n");
      out.write("                            </span>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- /input-group -->\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"index.html\"><i class=\"fa fa-dashboard fa-fw\"></i> Dashboard</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-bar-chart-o fa-fw\"></i> Charts<span class=\"fa arrow\"></span></a>\n");
      out.write("                            <ul class=\"nav nav-second-level\">\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"flot.html\">Flot Charts</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"morris.html\">Morris.js Charts</a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- /.nav-second-level -->\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"tables.html\"><i class=\"fa fa-table fa-fw\"></i> Tables</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"forms.html\"><i class=\"fa fa-edit fa-fw\"></i> Forms</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-wrench fa-fw\"></i> UI Elements<span class=\"fa arrow\"></span></a>\n");
      out.write("                            <ul class=\"nav nav-second-level\">\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"panels-wells.html\">Panels and Wells</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"buttons.html\">Buttons</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"notifications.html\">Notifications</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"typography.html\">Typography</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"icons.html\"> Icons</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"grid.html\">Grid</a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- /.nav-second-level -->\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-sitemap fa-fw\"></i> Multi-Level Dropdown<span class=\"fa arrow\"></span></a>\n");
      out.write("                            <ul class=\"nav nav-second-level\">\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\">Second Level Item</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\">Second Level Item</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"#\">Third Level <span class=\"fa arrow\"></span></a>\n");
      out.write("                                    <ul class=\"nav nav-third-level\">\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                    <!-- /.nav-third-level -->\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- /.nav-second-level -->\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-files-o fa-fw\"></i> Sample Pages<span class=\"fa arrow\"></span></a>\n");
      out.write("                            <ul class=\"nav nav-second-level\">\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"blank.html\">Blank Page</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"login.html\">Login Page</a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- /.nav-second-level -->\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.sidebar-collapse -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-static-side -->\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <div id=\"page-wrapper\">");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("	<div class=\"col-lg-12\">\n");
      out.write("		<h1 class=\"page-header\">Board Read</h1>\n");
      out.write("	</div>\n");
      out.write("	<!-- /.col-lg-12 -->\n");
      out.write("</div>\n");
      out.write("<!-- /.row -->\n");
      out.write("<div class=\"row\">\n");
      out.write("	<div class=\"col-lg-12\">\n");
      out.write("		<div class=\"panel panel-default\">\n");
      out.write("			<div class=\"panel-heading\">Board Read</div>\n");
      out.write("			<!-- /.panel-heading -->\n");
      out.write("			<div class=\"panel-body\">\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>BNO</label> <input class=\"form-control\" name=\"title\"\n");
      out.write("						readonly=\"readonly\" value='");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("					<p class=\"help-block\">Example block-level help text here.</p>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>Title</label> <input class=\"form-control\" name=\"title\"\n");
      out.write("						readonly=\"readonly\" value='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("					<p class=\"help-block\">Example block-level help text here.</p>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>Content</label>\n");
      out.write("					<textarea rows=\"5\" cols=\"50\" name=\"content\" class=\"form-control\">'");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("'</textarea>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>Writer</label> <input class=\"form-control\" name=\"writer\"\n");
      out.write("						value='");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("					<p class=\"help-block\">Example block-level help text here.</p>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<form id='actionForm' action=\"/board/list\" method=\"get\">\n");
      out.write("					<input type=\"hidden\" id=\"bno\" name=\"bno\"\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("\"> <input\n");
      out.write("						type=\"hidden\" name=\"pageNum\"\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("\"> <input\n");
      out.write("						type=\"hidden\" name=\"amount\"\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("\"> <input\n");
      out.write("						type=\"hidden\" name=\"keyword\"\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f7(_jspx_page_context))
        return;
      out.write("\"> <input\n");
      out.write("						type=\"hidden\" name=\"type\" value=\"");
      if (_jspx_meth_c_005fout_005f8(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("				</form>\n");
      out.write("\n");
      out.write("				<button type=\"button\" class=\"btn btn-default listBtn\">\n");
      out.write("					<a href='/board/list'>List</a>\n");
      out.write("				</button>\n");
      out.write("				<button type=\"button\" class=\"btn btn-default modBtn\">\n");
      out.write("					<a href='/board/modify?bno=");
      if (_jspx_meth_c_005fout_005f9(_jspx_page_context))
        return;
      out.write("'>Modify</a>\n");
      out.write("				</button>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<!-- /.panel-body -->\n");
      out.write("		</div>\n");
      out.write("		<!-- /.panel -->\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"col-lg-12\">\n");
      out.write("		<div class=\"panel panel-default\">\n");
      out.write("			<div class=\"panel-heading\">\n");
      out.write("				<i class=\"fa fa-comments fa-fw\"></i> Reply\n");
      out.write("				<button id='addReplyBtn' class=\"btn btn-primary btn-xs pull-right\">New\n");
      out.write("					Reply</button>\n");
      out.write("			</div>\n");
      out.write("			<!-- /.panel-heading -->\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"panel-body\">\n");
      out.write("				<ul class=\"chat\">\n");
      out.write("					<!-- start reply -->\n");
      out.write("					<li class=\"left clearfix\" data-rno='12'>\n");
      out.write("						<div>\n");
      out.write("							<div class=\"header\">\n");
      out.write("								<strong class=\"primary-font\">user00</strong> <small\n");
      out.write("									class=\"pull-right text-muted\">2024-06-07 12:50</small>\n");
      out.write("							</div>\n");
      out.write("							<p>Good good</p>\n");
      out.write("						</div> <!-- end reply -->\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				<!-- end ul -->\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<!--chat panel 추가   -->\n");
      out.write("\n");
      out.write("			<div class=\"panel-footer\"></div>\n");
      out.write("		</div>\n");
      out.write("		<!-- /.panel-body -->\n");
      out.write("	</div>\n");
      out.write("	<!-- /.col-lg-12 -->\n");
      out.write("</div>\n");
      out.write("<!-- /.row -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("	aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("	<div class=\"modal-dialog\">\n");
      out.write("		<div class=\"modal-content\">\n");
      out.write("			<div class=\"modal-header\">\n");
      out.write("				<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("					aria-hidden=\"true\">&times;</button>\n");
      out.write("				<h4 class=\"modal-title\" id=\"myModalLabel\">REPLY MODAL</h4>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"modal-body\">\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>Reply</label> <input class=\"form-control\" name='reply'\n");
      out.write("						value='New Reply!!@!'>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>Replyer</label> <input class=\"form-control\" name='replyer'\n");
      out.write("						value='replyer'>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label>Reply Date</label> <input class=\"form-control\"\n");
      out.write("						name='replyDate' value=''>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"modal-footer\">\n");
      out.write("				<button id=\"modalModBtn\" type=\"button\" class=\"btn btn-warning\">\n");
      out.write("					Modify</button>\n");
      out.write("				<button id='modalRemoveBtn' type=\"button\" class=\"btn btn-danger\">Remove</button>\n");
      out.write("				<button id='modalRegisterBtn' type=\"button\" class=\"btn btn-primary\">Register</button>\n");
      out.write("				<button id='modalCloseBtn' type=\"button\" class=\"btn btn-default\"\n");
      out.write("					data-dismiss=\"modal\">Close</button>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<!--modal-content  -->\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!--modal-dialog  -->\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!--modal  -->\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("	var actionForm = $(\"#actionForm\");\n");
      out.write("\n");
      out.write("	$(\".listBtn\").click(function(e) {\n");
      out.write("\n");
      out.write("		e.preventDefault();\n");
      out.write("		actionForm.find(\"input[name='bno']\").remove();\n");
      out.write("		actionForm.submit();\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	$(\".modBtn\").click(function(e) {\n");
      out.write("\n");
      out.write("		e.preventDefault();\n");
      out.write("		actionForm.attr(\"action\", \"/board/modify\");\n");
      out.write("		actionForm.submit();\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/reply.js\"></script>\n");
      out.write("<script>\n");
      out.write("	console.log(\"============\");\n");
      out.write("	console.log(\"jS TEST\");\n");
      out.write("	var bnoValue = '");
      if (_jspx_meth_c_005fout_005f10(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\n");
      out.write("	//for add Test()\n");
      out.write("	// replyService.add(\n");
      out.write("	// 		{reply:\"JS테스트 \",replyer:\"tester\",bno:bnoValue}\n");
      out.write("	// ,\n");
      out.write("	// function(result) {\n");
      out.write("	// 	alert(\"RESULT :\"+result);\n");
      out.write("	// }\n");
      out.write("	// );\n");
      out.write("\n");
      out.write("	//for List Test\n");
      out.write("	replyService.getList({\n");
      out.write("		bno : bnoValue,\n");
      out.write("		page : 1\n");
      out.write("	}, function(list) {\n");
      out.write("		for (var i = 0, len = list.length || 0; i < len; i++) {\n");
      out.write("			console.log(\"replyservice.getList의 list안에 데이터 집어넣는 로직 \")\n");
      out.write("			console.log(list[i]);\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	//for replyRemove Test(작동확인 완료 )\n");
      out.write("	// replyService.remove(23, function(count) {\n");
      out.write("	//     console.log(count);\n");
      out.write("	//     if (count === \"success\") {\n");
      out.write("	//         alert(\"REMOVED\");\n");
      out.write("	//     }\n");
      out.write("	// }, function(err) {\n");
      out.write("	//     alert(\"error-- \");\n");
      out.write("	// });\n");
      out.write("\n");
      out.write("	//for replyUpdate Test(작동확인 완료 )\n");
      out.write("	// replyService.update({\n");
      out.write("	// 	rno : 22,\n");
      out.write("	// 	bno : bnoValue,\n");
      out.write("	// 	reply : \"Modified Reply !!!!!\"\n");
      out.write("	// },function(result) {\n");
      out.write("	// 	alert(\"댓글 수정 테스트 완료 \");\n");
      out.write("\n");
      out.write("	// });\n");
      out.write("\n");
      out.write("// 	replyService.get(10, function(data) {\n");
      out.write("// 		console.log(data);\n");
      out.write("// 	});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- 아래 댓글목록 이벤트 처리 스크립 -->\n");
      out.write("<script>\n");
      out.write("	$(document)\n");
      out.write("			.ready(\n");
      out.write("					function() {\n");
      out.write("						var bnoValue = '");
      if (_jspx_meth_c_005fout_005f11(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("						var replyUL = $(\".chat\");\n");
      out.write("\n");
      out.write("						showList(1);\n");
      out.write("\n");
      out.write("						function showList(page) {\n");
      out.write("							console.log(\"showList함수에 접근했습니다 :\" + page);\n");
      out.write("\n");
      out.write("							// `page`가 1보다 작은 경우 1로 설정\n");
      out.write("							// page = page < 1 ? 1 : page;\n");
      out.write("\n");
      out.write("							replyService.getList(\n");
      out.write("											{\n");
      out.write("												bno : bnoValue,\n");
      out.write("												page : page || 1\n");
      out.write("											},\n");
      out.write("											function(replyCnt, list) {\n");
      out.write("\n");
      out.write("												console.log(\"replyService.getList함수에 접근했습니다 \")\n");
      out.write("												console.log(\"replyCnt: \"\n");
      out.write("														+ replyCnt);\n");
      out.write("												console.log(\"list: \" + list);\n");
      out.write("												console.log(list);\n");
      out.write("\n");
      out.write("												if (page == -1) {\n");
      out.write("													pageNum = Math\n");
      out.write("															.ceil(replyCnt / 10.0);\n");
      out.write("													showList(pageNum);\n");
      out.write("													return;\n");
      out.write("												}\n");
      out.write("\n");
      out.write("												var str = \"\";\n");
      out.write("\n");
      out.write("												if (list == null\n");
      out.write("														|| list.length == 0) {\n");
      out.write("													return;\n");
      out.write("												}\n");
      out.write("\n");
      out.write("												for (var i = 0, len = list.length || 0; i < len; i++) {\n");
      out.write("													str += \"<li class='left clearfix' data-rno='\" + list[i].rno + \"'>\";\n");
      out.write("													str += \" <div><div class='header'><strong class='primary-font'>[\"\n");
      out.write("															+ list[i].rno\n");
      out.write("															+ \"] \"\n");
      out.write("															+ list[i].replyer\n");
      out.write("															+ \"</strong>\";\n");
      out.write("													str += \" <small class='pull-right text-muted'>\"\n");
      out.write("															+ replyService\n");
      out.write("																	.displayTime(list[i].replyDate)\n");
      out.write("															+ \"</small></div>\";\n");
      out.write("													str += \" <p>\"\n");
      out.write("															+ list[i].reply\n");
      out.write("															+ \"</p></div></li>\";\n");
      out.write("												}\n");
      out.write("\n");
      out.write("												replyUL.html(str);\n");
      out.write("\n");
      out.write("												showReplyPage(replyCnt);\n");
      out.write("											}); // end function\n");
      out.write("						} // end showList\n");
      out.write("\n");
      out.write("						var modal = $(\".modal\");\n");
      out.write("						var modalInputReply = modal.find(\"input[name='reply']\");\n");
      out.write("						var modalInputReplyer = modal\n");
      out.write("								.find(\"input[name='replyer']\");\n");
      out.write("						var modalInputReplyDate = modal\n");
      out.write("								.find(\"input[name='replyDate']\");\n");
      out.write("\n");
      out.write("						var modalModBtn = $(\"#modalModBtn\");\n");
      out.write("						var modalRemoveBtn = $(\"#modalRemoveBtn\");\n");
      out.write("						var modalRegisterBtn = $(\"#modalRegisterBtn\");\n");
      out.write("\n");
      out.write("						$(\"#addReplyBtn\").on(\"click\", function(e) {\n");
      out.write("							modal.find(\"input\").val(\"\");\n");
      out.write("							modalInputReplyDate.closest(\"div\").hide();\n");
      out.write("							modal.find(\"button[id !='modalCloseBtn']\").hide();\n");
      out.write("							modalRegisterBtn.show();\n");
      out.write("							$(\".modal\").modal(\"show\");\n");
      out.write("						});\n");
      out.write("\n");
      out.write("						modalRegisterBtn.on(\"click\", function(e) {\n");
      out.write("							var reply = {\n");
      out.write("								reply : modalInputReply.val(),\n");
      out.write("								replyer : modalInputReplyer.val(),\n");
      out.write("								bno : bnoValue\n");
      out.write("							};\n");
      out.write("							replyService.add(reply, function(result) {\n");
      out.write("								alert(result);\n");
      out.write("								modal.find(\"input\").val(\"\");\n");
      out.write("								modal.modal(\"hide\");\n");
      out.write("\n");
      out.write("								// 등록 후 마지막 페이지를 다시 로드\n");
      out.write("								showList(-1);\n");
      out.write("							});\n");
      out.write("						});\n");
      out.write("\n");
      out.write("						// 댓글 조회 클릭 이벤트 처리 로직 \n");
      out.write("						$(\".chat\")\n");
      out.write("								.on(\n");
      out.write("										\"click\",\n");
      out.write("										\"li\",\n");
      out.write("										function(e) {\n");
      out.write("\n");
      out.write("											var rno = $(this).data(\"rno\");\n");
      out.write("\n");
      out.write("											replyService\n");
      out.write("													.get(\n");
      out.write("															rno,\n");
      out.write("															function(reply) {\n");
      out.write("\n");
      out.write("																modalInputReply\n");
      out.write("																		.val(reply.reply);\n");
      out.write("																modalInputReplyer\n");
      out.write("																		.val(reply.replyer);\n");
      out.write("																modalInputReplyDate\n");
      out.write("																		.val(\n");
      out.write("																				replyService\n");
      out.write("																						.displayTime(reply.replyDate))\n");
      out.write("																		.attr(\n");
      out.write("																				\"readonly\",\n");
      out.write("																				\"readonly\");\n");
      out.write("																modal\n");
      out.write("																		.data(\n");
      out.write("																				\"rno\",\n");
      out.write("																				reply.rno);\n");
      out.write("\n");
      out.write("																modal\n");
      out.write("																		.find(\n");
      out.write("																				\"button[id !='modalCloseBtn']\")\n");
      out.write("																		.hide();\n");
      out.write("																modalModBtn\n");
      out.write("																		.show();\n");
      out.write("																modalRemoveBtn\n");
      out.write("																		.show();\n");
      out.write("\n");
      out.write("																$(\".modal\")\n");
      out.write("																		.modal(\n");
      out.write("																				\"show\");\n");
      out.write("															})\n");
      out.write("										});\n");
      out.write("\n");
      out.write("						modalModBtn.on(\"click\", function(e) {\n");
      out.write("\n");
      out.write("							var reply = {\n");
      out.write("								rno : modal.data(\"rno\"),\n");
      out.write("								reply : modalInputReply.val()\n");
      out.write("							};\n");
      out.write("\n");
      out.write("							replyService.update(reply, function(result) {\n");
      out.write("\n");
      out.write("								alert(result);\n");
      out.write("								modal.modal(\"hide\");\n");
      out.write("								showList(pageNum);\n");
      out.write("							});\n");
      out.write("						});\n");
      out.write("\n");
      out.write("						modalRemoveBtn.on(\"click\", function(e) {\n");
      out.write("\n");
      out.write("							var rno = modal.data(\"rno\");\n");
      out.write("\n");
      out.write("							replyService.remove(rno, function(result) {\n");
      out.write("\n");
      out.write("								alert(result);\n");
      out.write("								modal.modal(\"hide\");\n");
      out.write("								showList(pageNum);\n");
      out.write("							});\n");
      out.write("\n");
      out.write("						});\n");
      out.write("\n");
      out.write("						// 댓글 페이지 번호를 출력하는 로직\n");
      out.write("						var pageNum = 1;\n");
      out.write("						var replyPageFooter = $(\".panel-footer\");\n");
      out.write("\n");
      out.write("						function showReplyPage(replyCnt) {\n");
      out.write("\n");
      out.write("							var endNum = Math.ceil(pageNum / 10.0) * 10;\n");
      out.write("							var startNum = endNum - 9;\n");
      out.write("\n");
      out.write("							var prev = startNum != 1;\n");
      out.write("							var next = false;\n");
      out.write("\n");
      out.write("							if (endNum * 10 >= replyCnt) {\n");
      out.write("								endNum = Math.ceil(replyCnt / 10.0);\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							if (endNum * 10 < replyCnt) {\n");
      out.write("								next = true;\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							var str = \"<ul class='pagination pull-right'>\";\n");
      out.write("\n");
      out.write("							if (prev) {\n");
      out.write("								str += \"<li class='page-item'><a class='page-link' href='\"\n");
      out.write("										+ (startNum - 1)\n");
      out.write("										+ \"'>Previous</a></li>\";\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							for (var i = startNum; i <= endNum; i++) {\n");
      out.write("								var active = pageNum == i ? \"active\" : \"\";\n");
      out.write("\n");
      out.write("								str += \"<li class='page-item \" + active + \"'><a class='page-link' href='\" + i + \"'>\"\n");
      out.write("										+ i + \"</a></li>\";\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							if (next) {\n");
      out.write("								str += \"<li class='page-item'><a class='page-link' href='\"\n");
      out.write("										+ (endNum + 1) + \"'>Next</a></li>\";\n");
      out.write("\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							str += \"</ul></div>\";\n");
      out.write("\n");
      out.write("							console.log(str);\n");
      out.write("\n");
      out.write("							replyPageFooter.html(str);\n");
      out.write("						}\n");
      out.write("\n");
      out.write("						replyPageFooter.on(\"click\", \"li a\", function(e) {\n");
      out.write("							e.preventDefault();\n");
      out.write("							console.log(\"page click\");\n");
      out.write("\n");
      out.write("							var targetPageNum = $(this).attr(\"href\");\n");
      out.write("\n");
      out.write("							console.log(\"targetPageNum: \" + targetPageNum);\n");
      out.write("\n");
      out.write("							pageNum = targetPageNum;\n");
      out.write("\n");
      out.write("							showList(pageNum);\n");
      out.write("						});\n");
      out.write("\n");
      out.write("					});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- /#page-wrapper -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /#wrapper -->\n");
      out.write("\n");
      out.write("<!--  Jqurey 추가  -->\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- DataTables JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\n");
      out.write("    <script src=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme JavaScript -->\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Page-Level Demo Scripts - Tables - Use for reference -->\n");
      out.write("    <script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("    	$('#dataTables-example').DataTable({\n");
      out.write("     	responsive: true\n");
      out.write("    });\n");
      out.write("    $(\".sidebar-nav\")\n");
      out.write("    	.attr(\"class\",\"sidebar-nav navbar-collapse collapse\")\n");
      out.write("    	.attr(\"aria-expanded\",'false')\n");
      out.write("    	.attr(\"style\",\"height:1px\");\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/board/get.jsp(24,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/board/get.jsp(30,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/board/get.jsp(36,71) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/board/get.jsp(42,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/board/get.jsp(49,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /WEB-INF/views/board/get.jsp(51,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent(null);
      // /WEB-INF/views/board/get.jsp(53,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f7_reused = false;
    try {
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent(null);
      // /WEB-INF/views/board/get.jsp(55,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      _jspx_th_c_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f8_reused = false;
    try {
      _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f8.setParent(null);
      // /WEB-INF/views/board/get.jsp(56,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
      if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      _jspx_th_c_005fout_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f9_reused = false;
    try {
      _jspx_th_c_005fout_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f9.setParent(null);
      // /WEB-INF/views/board/get.jsp(63,32) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f9 = _jspx_th_c_005fout_005f9.doStartTag();
      if (_jspx_th_c_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
      _jspx_th_c_005fout_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f10 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f10_reused = false;
    try {
      _jspx_th_c_005fout_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f10.setParent(null);
      // /WEB-INF/views/board/get.jsp(177,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f10.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f10 = _jspx_th_c_005fout_005f10.doStartTag();
      if (_jspx_th_c_005fout_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f10);
      _jspx_th_c_005fout_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f11 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f11_reused = false;
    try {
      _jspx_th_c_005fout_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f11.setParent(null);
      // /WEB-INF/views/board/get.jsp(229,22) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f11.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f11 = _jspx_th_c_005fout_005f11.doStartTag();
      if (_jspx_th_c_005fout_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f11);
      _jspx_th_c_005fout_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f11, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f11_reused);
    }
    return false;
  }
}
